version: '3.8'

services:
  librespot-auth:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: librespot-auth:latest
    container_name: librespot-auth
    volumes:
      - ./data:/app/data 
