version: '3.8'

services:
  librespot-auth:
    ports:
      - "39733:39733" # Map container port 39733 to host port 39733
    build:
      context: .
      dockerfile: Dockerfile
    image: librespot-auth:latest
    container_name: librespot-auth
    volumes:
      - ./data:/app/data 
